# Generated by Django 2.0 on 2021-04-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='Firstname', max_length=20)),
                ('lname', models.CharField(default='Lastname', max_length=20)),
                ('email', models.EmailField(default='Email', max_length=20, unique=True)),
            ],
        ),
    ]
