# Generated by Django 2.0 on 2021-04-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(default='Role', max_length=100)),
                ('Email', models.EmailField(default='Email', max_length=100, unique=True)),
                ('Password', models.CharField(default='passwd', max_length=100)),
                ('Is_Created', models.DateTimeField(auto_now_add=True)),
                ('Is_Verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookname', models.CharField(default='bname', max_length=100)),
                ('Authorname', models.CharField(default='aname', max_length=100)),
                ('Bookimage', models.ImageField(default='abc', upload_to='book-image/')),
                ('Book', models.FileField(default='abc', upload_to='Book-File/')),
                ('BookPrice', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='fname', max_length=100)),
                ('Lastname', models.CharField(default='lname', max_length=100)),
                ('Gender', models.CharField(default='Gender', max_length=100)),
                ('Profilepic', models.ImageField(default='abc', upload_to='seller-profile/')),
                ('Admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Admin')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
        migrations.AddField(
            model_name='user',
            name='Firstname',
            field=models.CharField(default='fname', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(default='Gender', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='Lastname',
            field=models.CharField(default='lname', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='Profilepic',
            field=models.ImageField(default='abc', upload_to='user-profile/'),
        ),
        migrations.AddField(
            model_name='book',
            name='Seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Seller'),
        ),
        migrations.AddField(
            model_name='user',
            name='Admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Admin'),
        ),
    ]
